import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/styles/globals.css";
import StoreProvider from "@/lib/Provider/StoreProvider";
import NavBar from "@/common/components/NavBar";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Spinner from "@/common/components/Spinner";

const inter = Open_Sans({
  weight: ["400", "700"], // Adjust the weights you need
  subsets: ["latin"], // Adjust the subsets you need
});

export const metadata: Metadata = {
  title: "Walia Song App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <Suspense fallback={<Spinner />}>
            <Toaster position="top-center" />
            <NavBar />

            {children}
          </Suspense>
        </body>
      </StoreProvider>
    </html>
  );
}
